language: php

php:
  - nightly

sudo: false

install:
  - composer selfupdate
  - composer install
  - composer require codeclimate/php-test-reporter satooshi/php-coveralls

script:
  - composer travis

after_success:
  - vendor/bin/test-reporter
  - vendor/bin/coveralls -v
