language: php

php:
  - nightly

sudo: false

install:
  - composer selfupdate
  - composer install
  - composer require codeclimate/php-test-reporter satooshi/php-coveralls

before_script:
  - sed --in-place 's/private $handles;/private $handles = [];/' vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php

script:
  - composer travis

after_success:
  - vendor/bin/test-reporter
  - vendor/bin/coveralls -v
